const courts = [
    "Aberystwyth Justice Centre",
    "Aldershot Magistrates' Court",
    "Barkingside  Magistrates' Court",
    "Barnsley Law Courts",
    "Barnstaple Magistrates', County and Family Court",
    "Barrow-in-Furness Magistrates' Court",
    "Basildon Magistrates' Court and Family Court",
    "Basingstoke Magistrates' Court",
    "Bath Law Courts",
    "Belmarsh Magistrates' Court",
    "Berwick upon Tweed Magistrates' Court",
    "Beverley Magistrates' Court and Hearing Centre",
    "Bexley Magistrates' Court",
    "Birmingham Magistrates' Court",
    "Blackburn Magistrates' Court",
    "Blackpool Magistrates' and Civil Court",
    "Bodmin Magistrates' Court",
    "Bolton Magistrates' Court",
    "Boston Magistrates' Court",
    "Bradford  and Keighley Magistrates' Court and Family Court",
    "Bridlington Magistrates' Court and Hearing Centre",
    "Brighton Magistrates' Court",
    "Bristol Magistrates' Court and Tribunals Hearing Centre",
    "Bromley Magistrates' Court",
    "Burnley Magistrates' Court",
    "Caernarfon  Justice Centre",
    "Cambridge Magistrates' Court",
    "Cannock Magistrates' Court",
    "Canterbury Magistrates' Court",
    "Cardiff  Magistrates' Court",
    "Carlisle Magistrates' Court",
    "Chelmsford Magistrates' Court and Family Court",
    "Cheltenham Magistrates' Court",
    "Chester Magistrates' Court",
    "North East Derbyshire & Dales (Chesterfield) Magistrates' Court",
    "City of London Magistrates' Court",
    "Colchester Magistrates' Court and Family Court",
    "Coventry Magistrates' Court",
    "Crawley Magistrates' Court",
    "Crewe (South Cheshire) Magistrates' Court",
    "Croydon Magistrates' Court",
    "Cwmbran Magistrates' Court",
    "Darlington Magistrates' Court and Family Court",
    "Derby Magistrates' Court",
    "Doncaster Justice Centre North",
    "Dudley Magistrates' Court",
    "Ealing Magistrates' Court",
    "East Berkshire Magistrates' Court, Slough",
    "Exeter Magistrates' Court - North and East Devon",
    "Folkestone Magistrates' Court",
    "Gateshead Magistrates' Court and Family Court",
    "Great Yarmouth Magistrates' Court and Family Court",
    "Grimsby Magistrates' Court and Family Court",
    "Guildford Magistrates' Court and Family Court",
    "Harrogate Justice Centre",
    "Hastings Magistrates' Court",
    "Hatfield Magistrates' Court",
    "Haverfordwest Magistrates' Court",
    "Hendon Magistrates' Court",
    "Hereford Justice Centre",
    "High Wycombe Magistrates' Court and Family Court",
    "Highbury Corner Magistrates' Court",
    "Horsham Magistrates' Court",
    "Hull and Holderness Magistrates' Court and Hearing Centre",
    "Huntingdon Law Courts",
    "Ipswich Magistrates' Court",
    "Isle of Wight Combined Court",
    "Kidderminster Magistrates' Court",
    "King's Lynn Magistrates' Court and Family Court",
    "Kirklees (Huddersfield) Magistrates' Court and Family Court",
    "Lancaster Courthouse",
    "Lavender Hill Magistrates' Court",
    "Leamington Spa Magistrates' Court",
    "Leeds Magistrates' Court and Family Court",
    "Leicester Magistrates' Court",
    "Lincoln Magistrates' Court",
    "Liverpool & Knowsley Magistrates' Court",
    "Llandrindod Wells Magistrates' and Family Court",
    "Llandudno Magistrates' Court",
    "Llanelli Law Courts",
    "Loughborough Magistrates' Court",
    "Luton and South Bedfordshire Magistrates' Court and Family Court",
    "Maidstone Magistrates' Court",
    "Manchester Magistrates' Court",
    "Mansfield Magistrates' and County Court",
    "Margate Magistrates' Court",
    "Medway Magistrates' Court and Family Court",
    "Merthyr Tydfil Combined Court Centre",
    "Mid and South East Northumberland Law Courts",
    "Milton Keynes Magistrates' Court and Family Court",
    "Mold Justice Centre",
    "Newcastle upon Tyne Magistrates' Court",
    "Newport (South Wales) Magistrates' Court",
    "Newton Abbot Magistrates' Court",
    "Newton Aycliffe Magistrates' Court",
    "North Somerset Magistrates' Court",
    "North Staffordshire Justice Centre",
    "North Tyneside Magistrates' Court",
    "Northampton Magistrates' Court",
    "Norwich Magistrates' Court and Family Court",
    "Nottingham Magistrates' Court",
    "Nuneaton Magistrates' Court",
    "Oxford and Southern Oxfordshire Magistrates' Court",
    "Peterborough Magistrates' Court",
    "Peterlee Magistrates' Court",
    "Plymouth Magistrates' Court",
    "Poole Magistrates' Court",
    "Port Talbot Justice Centre",
    "Portsmouth Magistrates' Court",
    "Preston Magistrates' Court",
    "Reading Magistrates' Court and Family Court",
    "Redditch Magistrates' Court",
    "Romford Magistrates' Court",
    "Salisbury Law Courts",
    "Scarborough Justice Centre",
    "Sefton Magistrates' Court",
    "Sevenoaks Magistrates' Court and Family Court",
    "Sheffield Magistrates' Court",
    "Skipton Magistrates' Court",
    "South Tyneside Magistrates' Court",
    "South Worcestershire Magistrates' Court",
    "Southend Magistrates' Court",
    "St Albans Magistrates' Court",
    "Staines Magistrates' Court and Family Court",
    "Stevenage Magistrates' Court",
    "Stockport Magistrates' Court",
    "Stratford Magistrates' Court",
    "Sunderland County, Family, Magistrates and Tribunal Hearings",
    "Swansea Magistrates' Court",
    "Swindon Magistrates' Court",
    "Tameside Magistrates' Court",
    "Taunton Magistrates' Court, Tribunals and Family Hearing Centre",
    "Teesside Magistrates' Court",
    "Telford Magistrates' Court",
    "Thames Magistrates' Court",
    "Truro Magistrates' Court",
    "Uxbridge Magistrates' Court",
    "Walsall Magistrates' Court",
    "Warrington Magistrates' Court",
    "Warwick Combined Court",
    "Wellingborough Magistrates' Court",
    "Welshpool Magistrates' Court",
    "West Cumbria Courthouse",
    "West Hampshire Magistrates' Court",
    "Westminster Magistrates' Court",
    "Weymouth Combined Court",
    "Wigan and Leigh Magistrates' Court",
    "Willesden Magistrates' Court",
    "Wimbledon Magistrates' Court",
    "Wirral Magistrates' Court",
    "Wolverhampton Magistrates' Court",
    "Worcester Justice Centre",
    "Worthing Magistrates' Court",
    "Wrexham Magistrates' Court",
    "Yeovil County, Family and Magistrates' Court",
    "York Magistrates' Court and Family Court"
]
module.exports = {courts}